In [0]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn import svm


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
dataset1=pd.read_csv('Fraud_Data.csv')
dataset1.head()

user_id          signup_time        purchase_time  ...  age    ip_address class
0    22058  2015-02-24 22:55:49  2015-04-18 02:47:11  ...   39  7.327584e+08     0
1   333320  2015-06-07 20:39:50  2015-06-08 01:38:54  ...   53  3.503114e+08     0
2     1359  2015-01-01 18:52:44  2015-01-01 18:52:45  ...   53  2.621474e+09     1
3   150084  2015-04-28 21:13:25  2015-05-04 13:54:50  ...   41  3.840542e+09     0
4   221365  2015-07-21 07:09:52  2015-09-09 18:40:53  ...   45  4.155831e+08     0

[5 rows x 11 columns]

In [0]:
dataset1.shape

(151112, 11)

In [0]:
dataset1.isnull().any()

user_id           False
signup_time       False
purchase_time     False
purchase_value    False
device_id         False
source            False
browser           False
sex               False
age               False
ip_address        False
class             False
dtype: bool

In [0]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   user_id         151112 non-null  int64  
 1   signup_time     151112 non-null  object 
 2   purchase_time   151112 non-null  object 
 3   purchase_value  151112 non-null  int64  
 4   device_id       151112 non-null  object 
 5   source          151112 non-null  object 
 6   browser         151112 non-null  object 
 7   sex             151112 non-null  object 
 8   age             151112 non-null  int64  
 9   ip_address      151112 non-null  float64
 10  class           151112 non-null  int64  
dtypes: float64(1), int64(4), object(6)
memory usage: 12.7+ MB


In [0]:
dataset1.describe(include='all')

user_id          signup_time  ...    ip_address          class
count   151112.000000               151112  ...  1.511120e+05  151112.000000
unique            NaN               151112  ...           NaN            NaN
top               NaN  2015-07-05 14:09:34  ...           NaN            NaN
freq              NaN                    1  ...           NaN            NaN
mean    200171.040970                  NaN  ...  2.152145e+09       0.093646
std     115369.285024                  NaN  ...  1.248497e+09       0.291336
min          2.000000                  NaN  ...  5.209350e+04       0.000000
25%     100642.500000                  NaN  ...  1.085934e+09       0.000000
50%     199958.000000                  NaN  ...  2.154770e+09       0.000000
75%     300054.000000                  NaN  ...  3.243258e+09       0.000000
max     400000.000000                  NaN  ...  4.294850e+09       1.000000

[11 rows x 11 columns]

In [0]:
dataset2=pd.read_csv('IpAddress_to_Country.csv')
dataset2.head()

lower_bound_ip_address  upper_bound_ip_address    country
0              16777216.0                16777471  Australia
1              16777472.0                16777727      China
2              16777728.0                16778239      China
3              16778240.0                16779263  Australia
4              16779264.0                16781311      China

In [0]:
dataset2.shape

(138846, 3)

In [0]:
dataset2.isnull().any()

lower_bound_ip_address    False
upper_bound_ip_address    False
country                   False
dtype: bool

In [0]:
dataset2.describe(include='all')

lower_bound_ip_address  upper_bound_ip_address        country
count             1.388460e+05            1.388460e+05         138846
unique                     NaN                     NaN            235
top                        NaN                     NaN  United States
freq                       NaN                     NaN          46868
mean              2.724532e+09            2.724557e+09            NaN
std               8.975215e+08            8.974979e+08            NaN
min               1.677722e+07            1.677747e+07            NaN
25%               1.919930e+09            1.920008e+09            NaN
50%               3.230887e+09            3.230888e+09            NaN
75%               3.350465e+09            3.350466e+09            NaN
max               3.758096e+09            3.758096e+09            NaN

In [0]:
dataset1

user_id          signup_time  ...    ip_address  class
0         22058  2015-02-24 22:55:49  ...  7.327584e+08      0
1        333320  2015-06-07 20:39:50  ...  3.503114e+08      0
2          1359  2015-01-01 18:52:44  ...  2.621474e+09      1
3        150084  2015-04-28 21:13:25  ...  3.840542e+09      0
4        221365  2015-07-21 07:09:52  ...  4.155831e+08      0
...         ...                  ...  ...           ...    ...
151107   345170  2015-01-27 03:03:34  ...  3.451155e+09      1
151108   274471  2015-05-15 17:43:29  ...  2.439047e+09      0
151109   368416  2015-03-03 23:07:31  ...  2.748471e+09      0
151110   207709  2015-07-09 20:06:07  ...  3.601175e+09      0
151111   138208  2015-06-10 07:02:20  ...  4.103825e+09      0

[151112 rows x 11 columns]

In [0]:
features_list = ['purchase_value','source','browser','sex','age']
numeric_indices = [0,4]
categorical_indices = [1,2,3]
target_variable = 'class'

In [0]:
 X = dataset1.loc[:, features_list]
 Y = dataset1.loc[:, target_variable]

 print('Variables explicatives : ', X.columns)
 print()

Variables explicatives :  Index(['purchase_value', 'source', 'browser', 'sex', 'age'], dtype='object')



In [0]:
# Divide dataset Train set & Test set 
print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=0)
print("...Done.")
print()

Dividing into train and test sets...
...Done.



In [0]:
# Convert pandas DataFrames to numpy arrays before using scikit-learn
print("Convert pandas DataFrames to numpy arrays...")
X_train = X_train.values
X_test = X_test.values
Y_train = Y_train.values
Y_test = Y_test.values
print("...Done")

print(X_train[0:5,:])
print(X_test[0:2,:])
print()
print(Y_train[0:5])
print(Y_test[0:2])

Convert pandas DataFrames to numpy arrays...
...Done
[[28 'SEO' 'FireFox' 'F' 18]
 [31 'SEO' 'Safari' 'M' 38]
 [65 'Ads' 'Safari' 'M' 29]
 [47 'Ads' 'Chrome' 'F' 29]
 [18 'SEO' 'IE' 'F' 22]]
[[22 'SEO' 'FireFox' 'F' 32]
 [38 'SEO' 'Chrome' 'M' 32]]

[0 0 0 1 0]
[0 0]


In [0]:
# Encoding categorical features and standardizing numerical features
print("Encoding categorical features and standardizing numerical features...")
print()
print(X_train[0:5,:])

# Normalization
numeric_transformer = StandardScaler()


# OHE / dummyfication
categorical_transformer = OneHotEncoder(drop='first')

featureencoder = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_indices),    
        ('num', numeric_transformer, numeric_indices)
        ]
    )

X_train = featureencoder.fit_transform(X_train)
print("...Done")
print(X_train[0:5,:])


Encoding categorical features and standardizing numerical features...

[[28 'SEO' 'FireFox' 'F' 18]
 [31 'SEO' 'Safari' 'M' 38]
 [65 'Ads' 'Safari' 'M' 29]
 [47 'Ads' 'Chrome' 'F' 29]
 [18 'SEO' 'IE' 'F' 22]]
...Done
[[ 0.          1.          1.          0.          0.          0.
   0.         -0.48857617 -1.75794245]
 [ 0.          1.          0.          0.          0.          1.
   1.         -0.32495267  0.56541794]
 [ 0.          0.          0.          0.          0.          1.
   1.          1.52944705 -0.48009424]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.54770602 -0.48009424]
 [ 0.          1.          0.          1.          0.          0.
   0.         -1.03398786 -1.29327037]]


In [0]:
# Train model
print("Train model...")
classifier =  LogisticRegressionCV() # regularized logit with regularization strength chosen by cross-val
classifier.fit(X_train, Y_train)
print("...Done.")

Train model...
...Done.


In [0]:
# Predictions on training set
print("Predictions on training set...")
Y_train_pred = classifier.predict(X_train)
print("...Done.")
print(Y_train_pred)
print()

Predictions on training set...
...Done.
[0 0 0 ... 0 0 0]



In [0]:
# Use X_test, and the same preprocessings as in training pipeline, 
# but call "transform()" instead of "fit_transform" methods (see example below)

print("Encoding categorical features and standardizing numerical features...")

X_test = featureencoder.transform(X_test)
print("...Done")
print(X_test[0:5,:])

Encoding categorical features and standardizing numerical features...
...Done
[[ 0.          1.          1.          0.          0.          0.
   0.         -0.81582318 -0.13159018]
 [ 0.          1.          0.          0.          0.          0.
   1.          0.05683551 -0.13159018]
 [ 0.          1.          0.          0.          0.          0.
   1.          1.2567412  -1.64177443]
 [ 0.          1.          1.          0.          0.          0.
   0.         -1.3066937   0.10074586]
 [ 0.          1.          0.          1.          0.          0.
   1.          1.03857653 -0.71243028]]


In [0]:
# Predictions on test set
print("Predictions on test set...")
Y_test_pred = classifier.predict(X_test)
print("...Done.")
print(Y_test_pred)
print()

Predictions on test set...
...Done.
[0 0 0 ... 0 0 0]



In [0]:
# WARNING : Use the same score as the one that will be used by Kaggle !
# Here, the f1-score will be used to assess the performances on the leaderboard
print("accuracy_score on train set : ", accuracy_score(Y_train, Y_train_pred))
print("accuracy_score on test set : ", accuracy_score(Y_test, Y_test_pred))
print("f1_score on train set : ", f1_score(Y_train, Y_train_pred))
print("f1_score on test set : ", f1_score(Y_test, Y_test_pred))

accuracy_score on train set :  0.9063161764705883
accuracy_score on test set :  0.9066966649020646
f1_score on train set :  0.0
f1_score on test set :  0.0


In [0]:
from sklearn.ensemble import AdaBoostRegressor 
regressor_ada = AdaBoostRegressor()
regressor_ada.fit(X_train, Y_train)
regressor_ada.score(X_test, Y_test)

0.0008783246978473213

In [0]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=50)
rf_classifier.fit(X_train, Y_train)
rf_classifier.score(X_train, Y_train)

0.9434558823529412

In [0]:
rf_classifier.score(X_test, Y_test)

0.9228427739544732

In [0]:
from sklearn.model_selection import GridSearchCV
rf_classifier_grid = RandomForestClassifier()
params = {"n_estimators": range(20, 50)}

classifier = GridSearchCV(cv=10, estimator = rf_classifier_grid, param_grid = params).fit(X_train, Y_train)

In [0]:
classifier.best_params_

{'n_estimators': 46}

In [0]:
classifier.best_estimator_.score(X_test, Y_test)

0.9231074642668078

In [0]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [0]:
from sklearn.linear_model import LogisticRegression
clf = RandomForestClassifier()
clf.fit(X_train, Y_train)
score = clf.score(X_test, Y_test)
score

0.9247617787188989